/*
 * File: app/view/MyPanel.js
 * Date: Sat Feb 25 2012 11:20:30 GMT+0400 (Russian Standard Time)
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('ImageApp.view.ImagePanel', {
    extend: 'ImageApp.view.ui.ImagePanel',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
    }
});